language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t mattgleich/auto-deploy-docker -f Dockerfile.dev .
script:
  - docker run -e CI=true mattgleich/auto-deploy-docker npm run test -- --coverage